### ISSUE TITLE
make:tactician file generation issue

### ISSUE THREAD

**Issue by JunaidQadirB** [joselfonseca/laravel-tactician#10]
`php artisan make:tactician /src/Commands/CommandName`

creates the files in `/app/CommandBus` whereas I have clearly specified a root path.

Current Behavior
---
`/app/CommandBus/Commands/CommandNameCommand`
`/app/CommandBus/Handlers/CommandNameHandler`

Expected behavior
---
at leaset

`/src/Commands/Commands/CommandNameCommand`
`/src/Commands/Handlers/CommandNameHandler`

OR

`/src/Commands/CommandNameCommand`
`/src/Commands/CommandNameHandler`

Also, It would be nicer if there were a flag like `--bare` to skip creating `Commands` and 'Handlers' folders.

**Comment by joselfonseca** [comment]
Sorry this took too long, I hope is still relevant but take a look at this, https://github.com/joselfonseca/laravel-tactician/commit/4a0f824ad4a5c992e40b365caa5f948c679b643c .Will tag it soon with support for laravel 6.
