### ISSUE TITLE
Publishes command isn't working

### ISSUE THREAD

**Issue by joruro** [joselfonseca/laravel-tactician#3]
Hey,

Your service provider hasn't the `publishes` method. It requires this method in order to run `php artisan vendor:publish` without problems.

```
{
  "error": {
    "type": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "message": "Call to undefined method Joselfonseca\\LaravelTactician\\Providers\\LaravelTacticianServiceProvider::publishes()",
    "file": "/project/vendor/joselfonseca/laravel-tactician/src/Providers/LaravelTacticianServiceProvider.php",
    "line": 63
  }
}
```

Profile:
Laravel 4
joselfonseca/laravel-tactician    0.3.2

**Comment by joselfonseca** [comment]
Hi there,

It actually has it here https://github.com/joselfonseca/laravel-tactician/blob/master/src/Providers/LaravelTacticianServiceProvider.php#L63

I do not think this will work in Laravel 4. Never test it there and it was intended for laravel 5.1+.
